### ISSUE TITLE
Sidebar overlapping with content

### ISSUE THREAD

**Issue by darvid7** [telstra/swagger-platform#35]
I don't think this is intentional 😛
Ignore if already known

<img width="1132" alt="screen shot 2018-07-08 at 4 13 53 pm" src="https://user-images.githubusercontent.com/11433468/42417296-ff2b1728-82c9-11e8-918e-0fb54ea6ed7c.png">
<img width="1294" alt="screen shot 2018-07-08 at 4 11 41 pm" src="https://user-images.githubusercontent.com/11433468/42417297-ff9646ec-82c9-11e8-8506-295a7c56b0b0.png">

**Comment by PatrickShaw** [comment]
Oh wow this wasn't a thing last time i checked. What browser are you using?

**Comment by darvid7** [comment]
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by PatrickShaw** [comment]
Quick update @darvid7 
Turns out I did not have the correct node_modules installed while developing. @calebj0seph has a fixes for a few things so worry not 👍
